// +build autogen,!windows

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	ContainerdCommitID string = "9048e5e50717ea4497b757314bad98ea3763c145"
	RuncCommitID       string = "9c2d8d184e5da67c95d601382adf14862e4f2228"
	InitCommitID       string = "949e6facb77383876aeff8a6944dde66b3089574"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
