// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "3385658"
	Version            string = "17.06.0-dev"
	BuildTime          string = "2019-11-20T01:51:46.294133890+00:00"
	IAmStatic          string = "true"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
